export const TIMING = {
  QUESTION_TRANSITION_DELAY: 3000,
  REVEAL_DELAY: 5000,
  COUNTDOWN_WARNING_THRESHOLD: 3,
  TIMER_INTERVAL: 1000,
  DEFAULT_TIME_LIMIT: 5,
  MIN_TIME_LIMIT: 5,
  MAX_TIME_LIMIT: 30,
  CONNECTION_TIMEOUT: 10000,
  GAME_START_DELAY: 500,
  ROOM_JOIN_DELAY: 1000,
} as const

export const QUESTION_COUNT = {
  DEFAULT: 10,
  MIN: 5,
  MAX: 50,
} as const

